pull_request_rules:
  - name: copy probe
    conditions:
      - base=main
    actions:
      label:
        add: [copied]
      copy:
        branches:
          - pipe|x
          - semi;colon
        ignore_conflicts: true
